### ISSUE TITLE
Productionalize Beta Feature (Add/Edit/Remove Parcels)

### ISSUE THREAD

**Issue by jmdevita** [jmdevita/parcel-ha#38]
To move beta feature (add/edit/remove) out of beta, the following should be implemented:
- Tests for Add/Edit/Remove
- Daily checker for Account Token (Raises Issue if check failed to user)
- Convert Carrier string to dynamically updated table (from coordinator)

**Comment by georgefahmy** [comment]
can you provide an example configuration with the account token? i can't seem to get the beta features to work following the directions.

**Comment by PineappleEmperor** [comment]
Do you see anything in the logs?
Did you grab the cookie successfully on this step?

![Image](https://github.com/user-attachments/assets/9f6352d5-5331-44a3-94fb-bf30c9d3b888)

Can you paste the yaml of the action you tried to run, e.g.
```
action: parcelapp.add_parcel
data:
  parcel_name: Test 📋
  tracking_number: "12345"
  courier: pholder
```
